- docs/contributing.md
- docs/index.md
- docs/syntax.md
- docs/wealth_dynamics_md.md
- myst_parser/block_tokens.py
Also add labelled math to example
> DOCS add contributing guide and syntax summary

- myst_parser/docutils_renderer.py
- myst_parser/sphinx_parser.py
- tests/sphinx_directives.json
- tests/test_docutils_renderer.py
The only addition is that the `SphinxRenderer` handles cross-references with the `pending_xref` node.
> Split SphinxRenderer from DocutilsRenderer

- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/sphinx_parser.py
- pytest.ini
- tests/sphinx_directives.json
- tests/test_docutils_renderer.py
Also add error reporting for YAML block parsing.
> Add colon syntax for directive options.

- docs/using/syntax.md
- myst_parser/block_tokens.py
- myst_parser/docutils_renderer.py
- myst_parser/html_renderer.py
- tests/test_renderers/test_docutils.py
- tests/test_sphinx/sourcedirs/basic/content.md
- tests/test_syntax/test_ast.py
- tests/test_syntax/test_ast/test_block_break_basic_strings0_.yml
- tests/test_syntax/test_ast/test_block_break_escaped_strings3_.yml
- tests/test_syntax/test_ast/test_block_break_following_content_no_space_strings8_.yml
- tests/test_syntax/test_ast/test_block_break_following_content_strings5_.yml
- tests/test_syntax/test_ast/test_block_break_following_space_strings6_.yml
- tests/test_syntax/test_ast/test_block_break_follows_list_strings7_.yml
- tests/test_syntax/test_ast/test_block_break_indent_2_strings1_.yml
- tests/test_syntax/test_ast/test_block_break_indent_4_strings2_.yml
- tests/test_syntax/test_ast/test_block_break_inline_strings4_.yml
- tests/test_syntax/test_ast/test_comment_indent_2_strings1_.yml
- tests/test_syntax/test_ast/test_role_basic_strings0_.yml
- tests/test_syntax/test_ast/test_role_escaped_strings3_.yml
- tests/test_syntax/test_ast/test_role_external_code_strings11_.yml
- tests/test_syntax/test_ast/test_role_external_emphasis_strings7_.yml
- tests/test_syntax/test_ast/test_role_external_math_strings9_.yml
- tests/test_syntax/test_ast/test_role_indent_2_strings1_.yml
- tests/test_syntax/test_ast/test_role_indent_4_strings2_.yml
- tests/test_syntax/test_ast/test_role_inline_strings4_.yml
- tests/test_syntax/test_ast/test_role_internal_code_strings10_.yml
- tests/test_syntax/test_ast/test_role_internal_emphasis_strings6_.yml
- tests/test_syntax/test_ast/test_role_internal_math_strings8_.yml
- tests/test_syntax/test_ast/test_role_multiple_strings5_.yml
Following from discussion in ExecutableBookProject/sphinx-notebook#12,
I have added the `BlockBreak` AST token, which parses lines beginning with `+++`.
In the docutils renderer, these lines are converted to `comment` nodes, so they won't be rendered in output text, but also with an added class, so they can be identified by potential sphinx transform extensions:
```
+++ a block break
```
goes to Markdown AST:
```yaml
type: Document
footnotes: {}
children:
- content: a block break
range:
- 1
- 1
raw: +++ a block break
type: BlockBreak
```
and docutils AST:
```xml
<document source="">
<comment classes="block_break" xml:space="preserve">
a block break
```
> Add `BlockBreak` token (`+++`)

- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/parse_directives.py
- tests/test_renderers/test_parse_directives.py
- tests/test_renderers/test_parse_directives/test_parsing_Note__a_.yml
- tests/test_renderers/test_parse_directives/test_parsing_Note_a__.yml
- tests/test_renderers/test_roles_directives/test_directive_options_error_block_style_text0_.xml
- tests/test_renderers/test_roles_directives/test_directive_options_error_colon_style_text1_.xml
fixes #55 
Firstly, the `directive block text -> arguments, options, body` parsing has been separated into to a standalone module.
Secondly, the docutils parser [here](https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/parsers/rst/states.py#L2118)
does not rigidly specify the structure of the directive block:
```restructuredtext
.. <name>:: <arguments>
<option block>
<body>
```
Instead, if no required/optional arguments are specified (by the directive class), and no `<option block>` is used, the `<body>` block can start at `<arguments>`. Example:
```restructuredtext
.. note:: This is body text
```
This PR allows MyST to implement that logic. 
````markdown
```{note} This is body text
```
````
Note the rST parser also allows for the options to …
> Improve directive block parsing

- README.md
- docs/conf.py
- docs/develop/contributing.md
- docs/develop/test_infrastructure.md
- docs/examples/index.md
- docs/using/index.md
- docs/using/install.md
- docs/using/syntax.md
- myst_parser/__init__.py
- myst_parser/sphinx_parser.py
- setup.py
- The GitHub folder has been renamed from  `myst_parser` to `MyST-Parser`
- The package name has been changed from `myst_parser` to `myst-parser`
- Also changed doc references from Myst to MyST
Better sooner rather than later!
@choldgraf this will need to be changed in the MyST-NB setup
@rossbar @mmcky @jstac @akhmerov you are potential users that I can think of that this might affect.
> Change project/package name

- docs/using/syntax.md
- myst_parser/block_tokens.py
- tests/test_commonmark/test_commonmark.py
- tests/test_renderers/test_docutils.py
- tests/test_syntax/test_ast.py
- tests/test_syntax/test_ast/test_link_references_ref_escape_strings3_.yml
- tests/test_syntax/test_ast/test_link_references_ref_first_strings0_.yml
- tests/test_syntax/test_ast/test_link_references_ref_last_strings1_.yml
- tests/test_syntax/test_ast/test_link_references_ref_syntax_strings2_.yml
Although `Footnote` is used by mistletoe, this is incorrect because it actually refers to <https://spec.commonmark.org/0.28/#link-reference-definitions>, rather than what would generally be considered a footnote: <https://www.markdownguide.org/extended-syntax/#footnotes>.
There is also discussion about link definitions vs footnotes here: <https://talk.commonmark.org/t/footnote-extensions-vs-link-reference-definition/2571>.
> Rename `Footnote` to `LinkDefinition`.

- myst_parser/docutils_renderer.py
- tests/test_renderers/test_docutils.py
This closes #89 , but doesn't improve the extra things that @chrisjsewell mentioned as "like to have"s for the xref functionality. For that, I've opened up a new issue: https://github.com/ExecutableBookProject/MyST-Parser/issues/91
This adds a test to make sure that cross-refs are correctly in there as literals until they get resolved.
> fixing xref literal bug

- docs/.gitignore
- docs/api/index.md
- docs/api/renderers.rst
- docs/api/sphinx_parser.rst
- docs/api/tokens.rst
- docs/conf.py
- docs/index.md
- docs/package_api.md
- docs/using/syntax.md
- docs/using/use_api.md
- myst_parser/__init__.py
- myst_parser/block_tokens.py
- myst_parser/sphinx_parser.py
- setup.py
Utilising the new documentation for [mistletoe-ebp](https://mistletoe-ebp.readthedocs.io) 😄 
@choldgraf I believe this closes #19
See: https://256-240151150-gh.circle-artifacts.com/0/html/api/index.html
> Improve API documentaion and add Inter-sphinx references

- .vscode/settings.json
- docs/api/tokens.rst
- docs/conf.py
- myst_parser/__init__.py
- myst_parser/block_tokens.py
- myst_parser/docutils_renderer.py
- myst_parser/html_renderer.py
- myst_parser/json_renderer.py
- myst_parser/span_tokens.py
- setup.py
- tests/test_syntax/test_ast.py
- tests/test_syntax/test_ast/test_front_matter_basic_strings0_.yml
This update allows us to drop most of the span token patching code, and we now use the `Math` token directly from mistletoe.
It also improves how token sets are instantiated within the renderers, making it a lot easier to swap in/out tokens to be included in the parse.
> Update to `mistletoe-ebp==0.9.4a2` dependency

- myst_parser/__init__.py
- myst_parser/block_tokens.py
This is to make it more compatible with upstream changes (this subclass of `Document` will eventually be removed, in favour of directly using the one from mistletoe).
> Remove specific arguments from `Document.read`

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/sphinx_directives.md
- tests/test_renderers/fixtures/tables.md
- tests/test_sphinx/sourcedirs/basic/content.md
- tests/test_sphinx/test_sphinx_builds/test_basic.html
- tests/test_sphinx/test_sphinx_builds/test_basic.xml
Closes #127 
I added a paragraph wrapper to `render_table_row`, and modified the existing tests to capture this wrapper. 
Let me know if a new test should be added to this PR, making sure urls inside the table are rendered as references, or something of the sort.
> Add paragraph wrapper to table rows

- .github/workflows/artifact.yml
- docs/conf.py
- setup.py
This uses the `sphinx-book-theme` for the documentation. Also adds a github action that previews the CircleCI artifact (which won't work on this PR but will work on subsequent ones)
Demo here: https://350-240151150-gh.circle-artifacts.com/0/html/index.html
For some reason, the glyphs in the admonition blocks aren't showing up in this theme. This seems somehow related to myst_parser, since it works fine in the same PR for myst_nb (https://github.com/ExecutableBookProject/MyST-NB/pull/164)
> using sphinx book theme docs

- myst_parser/docutils_renderer.py
closes https://github.com/executablebooks/jupyter-book/issues/695
This tackles an edge-case where the code fence is used with an empty space after the back-ticks
I'm not quite sure how to test this, since it seems like it should be part of the commonmark test suite but they apparently don't test for it (?)
> Fix bug if fence language is an empty space

- docs/using/intro.md
- docs/using/syntax.md
This adds some more getting started information and background on Sphinx / parsers / roles / directives / etc. It tries to address a few more of @amueller's points about assumptions we're making about readers.
The biggest addition is a section describing what directives / roles are, their structure, and a bit of information about what they do. I'm thinking of this content as a complement to what is in `syntax.md`, which is more like a "reference" and complete set of information.
> adding more getting started docs

- .circleci/config.yml
- .gitignore
- .vscode/settings.json
- README.md
- docs/develop/contributing.md
- docs/using/intro.md
- setup.py
Sphinx was originally set as an extra requirement, when myst-parser contained plugins for the markdown parser. This is no longer the case, so it is now not likely that the package would be used without sphinx, and just overcomplicates things to have to install `myst-parser[sphinx]`, rather than just `myst-parser`.
Note the `sphinx` extra has been left in (as an empty list) so that existing requirements files do not break.
> Move sphinx into main requirements

- docs/index.md
- docs/using/intro.md
Adds some notes about how users can use MyST _alongside_ rST. @asmeurer think this would help get this message across?
here's how it looks: https://myst-parser--182.org.readthedocs.build/en/182/using/intro.html#enable-myst-in-sphinx
> using rst notes

- myst_parser/mocking.py
- tests/test_renderers/fixtures/docutil_directives.md
- tests/test_renderers/fixtures/docutil_roles.md
See: https://docutils.sourceforge.io/docs/ref/rst/roles.html#specialized-roles
> Add functionality to use docutils specialized role

- codecov.yml
- docs/conf.py
- docs/using/intro.md
- docs/using/syntax.md
- myst_parser/__init__.py
- myst_parser/cli/benchmark.py
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- myst_parser/sphinx_parser.py
- setup.py
- tests/test_renderers/test_error_reporting.py
- tests/test_renderers/test_fixtures.py
- tests/test_renderers/test_myst_refs.py
- tests/test_sphinx/sourcedirs/conf_values/conf.py
- tests/test_sphinx/sourcedirs/conf_values/index.md
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_conf_values.html
- tests/test_sphinx/test_sphinx_builds/test_conf_values.xml
This centralises parsing configuration storage and validation, meaning it only has to be updated in a single place.
Also moved from using `texmath_plugin` to `dollarmath_plugin`
> 👌 IMPROVE: Math Parsing

- docs/conf.py
- docs/index.md
- docs/using/howto.md
- docs/using/intro.md
- docs/using/snippets/include-md.md
- docs/using/snippets/include-rst.rst
- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/mocking.py
- setup.py
- tests/test_renderers/fixtures/eval_rst.md
- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_renderers/test_fixtures.py
- tests/test_sphinx/sourcedirs/references/index.md
- tests/test_sphinx/test_sphinx_builds/test_references.html
- tests/test_sphinx/test_sphinx_builds/test_references.resolved.xml
- tests/test_sphinx/test_sphinx_builds/test_references.xml
- tox.ini
Adds support the `eval-rst` directive, similar to recommonmark's version.  Fixes #164.
Examples (which I added unit tests for):
Links:
```{eval-rst}
`MyST Parser <https://myst-parser.readthedocs.io/>`_
```
Bold text:
```{eval-rst}
**bold**
```
Or as I'll use it in [ParlAI](https://github.com/facebookresearch/parlai). I tested this in my own repo.
```{eval-rst}
.. automodule:: parlai.utils.bpe
:members:
```
> ✨ Add the eval-rst directive

- codecov.yml
- docs/using/intro.md
- docs/using/syntax.md
- myst_parser/__init__.py
- myst_parser/main.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/conf.py
Instead of overriding all of `mathjax_config`, now only the "tex2jax" key will be added/replaced.
If the user has specifically set  `mathjax_config["tex2jax"]`, a warning will also be logged, that it is being overriden.
> 👌 IMPROVE: mathjax_config override

- docs/using/intro.md
- myst_parser/myst_refs.py
- myst_parser/sphinx_renderer.py
- tests/test_renderers/fixtures/syntax_elements.md
- tests/test_renderers/test_myst_refs/duplicate.xml
- tests/test_renderers/test_myst_refs/missing.xml
- tests/test_sphinx/sourcedirs/references_singlehtml/conf.py
- tests/test_sphinx/sourcedirs/references_singlehtml/index.md
- tests/test_sphinx/sourcedirs/references_singlehtml/other/index.md
- tests/test_sphinx/sourcedirs/references_singlehtml/other/other.md
- tests/test_sphinx/sourcedirs/references_singlehtml/other/other2.md
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_includes.xml
- tests/test_sphinx/test_sphinx_builds/test_references.xml
- tests/test_sphinx/test_sphinx_builds/test_references_singlehtml.html
- tests/test_sphinx/test_sphinx_builds/test_references_singlehtml.resolved.xml
- tests/test_sphinx/test_sphinx_builds/test_references_singlehtml.xml
- tox.ini
These reference resolutions are passed to the "missing-reference" event, and require the `node["refdoc"]` attribute to be available, which was missing for `[text](./path/to/file.md)` type references.
> 🐛 FIX: doc reference resolution for singlehtml/latex

- docs/using/syntax-optional.md
> [🐛 FIX,  📚 DOCS] Typo `myst-paser` -> `myst-parser`

- myst_parser/docutils_renderer.py
This is a small fix to prevent front-matter dates from breaking the docutils parser.
@chrisjsewell could you recommend where a test should go for this?
closes https://github.com/executablebooks/MyST-Parser/issues/252
> 🐛 FIX: allow dates to be parsed in frontmatter

- CHANGELOG.md
- myst_parser/__init__.py
This brings in the datetime bugfix...the only other PRs were documentation typo fixes I believe
> 🚀 RELEASE: v0.12.10

- README.md
Along the way, fix capitalization and add a few more links:
CommonMark, Docutils, Sphinx.
For the contributing guide url I used "index.html"
https://myst-parser.readthedocs.io/en/latest/develop/index.html
Alternatively one could just replace "master" with "develop"
in the former url, and point to "contributing.html":
https://myst-parser.readthedocs.io/en/latest/develop/contributing.html
Pros and cons of each choice. The page "index.html" links
to the code of conduct of the Executable Book Project and
to the page "contributing.html". The page "contributing.html"
links to the Executable Book Project's contributing guide.
> 📚 DOCS: `link to contributing guide in README.md

- docs/conf.py
- setup.py
Bump into this in #274 so pinning as mentioned in https://github.com/executablebooks/MyST-Parser/pull/274#issuecomment-748017517.
> 🔧 MAINT: pin sphinxcontrib-bibtex & fix deprecated doc config

- docs/using/use_api.md
Fix #247.
Took the code from https://github.com/executablebooks/MyST-Parser/issues/247#issuecomment-687251411.
> 📚 DOCS: Update API for default parser.

- myst_parser/main.py
Show only names of substitutions, rather than the full key/value dictionary
> 👌 IMPROVE: `MdParserConfig.substitutions`

- myst_parser/mocking.py
Suggest using `{eval-rst}` and link to its documentation.
As suggested in https://github.com/executablebooks/MyST-Parser/issues/284#issuecomment-756434092
> 👌 IMPROVE: Error msg for unimplemented directives

- myst_parser/parse_directives.py
- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_sphinx/test_sphinx_builds/test_includes.html
- tests/test_sphinx/test_sphinx_builds/test_includes.xml
docutils directives always expect options to be strings, but we parse them as YAML, and so e.g. ints and floats should be converted back. Also None should be converted to an empty string.
fixes #289
> 🐛 FIX: convert directive option values to string

- docs/develop/architecture.md
- docs/using/syntax-optional.md
- myst_parser/directives.py
- myst_parser/docutils_renderer.py
- myst_parser/html_to_nodes.py
- myst_parser/main.py
- myst_parser/mocking.py
- myst_parser/sphinx_renderer.py
- tests/test_html/test_html_to_nodes.py
- tests/test_sphinx/sourcedirs/substitutions/index.md
- tests/test_sphinx/test_sphinx_builds/test_substitutions.html
- tests/test_sphinx/test_sphinx_builds/test_substitutions.xml
Parse inline substitutions without block syntax rules, unless the substitution starts with a directive.
fixes #282
> 👌 IMPROVE: substitution logic

- docs/api/renderers.rst
- docs/conf.py
- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/syntax_elements.md
This allows the `DocInfo` transform to correctly convert
bibliographic keys to specific nodes, which can be used by other transforms.
> 🐛 FIX: Render front-matter as `field_list`

- docs/conf.py
- docs/using/intro.md
- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- myst_parser/sphinx_parser.py
- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_renderers/fixtures/syntax_elements.md
- tests/test_renderers/test_error_reporting.py
- tests/test_renderers/test_fixtures.py
- tests/test_sphinx/conftest.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/conf.py
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.xml
Can be added globally,
as configuration `myst_html_meta`,
or at the document level,
in the front-matter under key `html_meta`.
> ✨ NEW: Add setting HTML metadata

- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- tests/test_sphinx/test_sphinx_builds/test_footnotes.html
- tests/test_sphinx/test_sphinx_builds/test_footnotes.xml
If the label is an integer, then it will always use this integer for the rendered label (i.e. they are manually numbered).
fixes #195
> 👌 IMPROVE: integer footnote references

- myst_parser/docutils_renderer.py
- setup.py
In particular, this fixes missing line mappings for table rows and their children
> ⬆️ UPGRADE: markdown-it-py v0.6.2

- myst_parser/docutils_renderer.py
- tests/test_sphinx/sourcedirs/gettext/conf.py
- tests/test_sphinx/sourcedirs/gettext/index.md
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_gettext.pot
If you have Markdown like:
```md
* My **Awesome** markdown
```
Sphinx needs to be passed `My **Awesome** markdown`.
The code does not do that.
This is the same bug as in recommonmark: https://github.com/readthedocs/recommonmark/pull/187 which had originally been fixed by a Sphinx maintainer, and which I more recently fixed (though recommonmark is very behind on merging PRs).
As you can see in the code for paragraphs, sometimes the original Markdown content is not where you expect it. So far, I've only tested a few tokens.
cc @choldgraf
> 👌 IMPROVE: Store rawtext in AST nodes (for gettext)

- docs/using/howto.md
- myst_parser/docutils_renderer.py
- myst_parser/html_to_nodes.py
- myst_parser/myst_refs.py
- myst_parser/sphinx_renderer.py
- tests/test_renderers/fixtures/containers.md
- tests/test_renderers/fixtures/sphinx_directives.md
- tests/test_renderers/test_fixtures.py
All parsing warnings are assigned a type/subtype,
and also the messages are appended with them.
These warning types can be suppressed
with the sphinx `suppress_warnings` config option.
> ✨ NEW: Add warning types `myst.subtype`

- tests/test_sphinx/sourcedirs/gettext/index.md
- tests/test_sphinx/test_sphinx_builds/test_gettext.pot
This will be relevant to an issue I'm going to open on mdformat.
> 🧪 TESTS: Add extra backticks case for gettext

- .flake8
- .pre-commit-config.yaml
- myst_parser/docutils_renderer.py
- myst_parser/mocking.py
- myst_parser/myst_refs.py
- myst_parser/parse_html.py
- tox.ini
- add flake8-comprehensions and flake8-bugbear
- move mypy cli arg to configuration file
- use flake8 `extend-ignore` to extend, not override, default ignores
> 🔧 MAINTAIN: Linter improvements

- docs/api/sphinx_parser.rst
- myst_parser/sphinx_parser.py
- setup.py
- tests/test_sphinx/test_sphinx_builds/test_basic.html
- tests/test_sphinx/test_sphinx_builds/test_commonmark_only.html
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.html
- tests/test_sphinx/test_sphinx_builds/test_footnotes.html
- tests/test_sphinx/test_sphinx_builds/test_includes.html
- tests/test_sphinx/test_sphinx_builds/test_references.html
- tests/test_sphinx/test_sphinx_builds/test_references_singlehtml.html
This adds the missing setting that has been added to the RST parser in docutils v0.17.
Although, perhaps it is better to not have `settings_spec` copy/pasted here, but just inherit it
> 🐛 FIX: docutils `v0.17` compatibility

- setup.py
The EventManager initializer changed signature between 2.0 and 2.1.
MyST-Parser uses the >= 2.1 signature.
https://github.com/sphinx-doc/sphinx/blob/v2.0.1/sphinx/events.py#L44-L45
https://github.com/sphinx-doc/sphinx/blob/v2.1.0/sphinx/events.py#L50-L53
> 🔧 MAINTAIN: Increase sphinx lower pinning to `v2.1`

- myst_parser/__init__.py
- myst_parser/cli.py
- myst_parser/sphinx_renderer.py
- tox.ini
Mainly adds `check_untyped_defs = true` so that mypy does some basic type analysis even when type annotations are not present.
> 🔧 MAINTAIN: Stricter mypy config

- myst_parser/docutils_renderer.py
- myst_parser/mocking.py
- tests/test_renderers/fixtures/reporter_warnings.md
When a nested parse is performed and `match_titles=False`,
this informs that headers are not supported in this block,
as is the case for example with admonitions:
````markdown
```{note}
```
````
A warning (of type `myst.nested_header`) is now emitted when this occurs.
> 👌 IMPROVE: Add warning for nested headers

- docs/conf.py
- docs/using/intro.md
- docs/using/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/conf.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/index.md
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.html
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.xml
Allow display math (i.e. `$$`) within an inline context.
Exposes functionality added in: https://github.com/executablebooks/mdit-py-plugins/pull/19
> ✨ NEW: Add `dmath_double_inline` configuration option

- docs/conf.py
- docs/using/intro.md
- docs/using/syntax-optional.md
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/conf.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/index.md
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.html
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.xml
Task lists utilise the [markdown-it-py tasklists plugin](markdown_it:md/plugins),
and are applied to Markdown list items starting with `[ ]` or `[x]`.
```markdown
```
> ✨ NEW: Add `tasklist` extension

- docs/using/howto.md
When following the instructions as written, I got the error:
`WARNING: Unknown directive type "literal-include".`
But it worked as expected when I replaced `{include-literal}` with the Spinx directive `{literalinclude}`. (Also, I notice that `{literalinclude}` is the directive being used in this file to include `example-include.md`.)
Using:
* sphinx                             3.4.3
* jupyter-book                  0.10.0
* myst-parser                   0.13.3
> 📚 DOCS: literalinclude instead of include-literal

- myst_parser/docutils_.py
- myst_parser/sphinx_.py
- myst_parser/sphinx_renderer.py
- tests/test_docutils.py
supercedes #414
cc @cpitclaudel
closes #417 
closes #388
> 🔧 MAINTAIN: Support `include` parser option in RST

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/syntax_elements.md
The doctrees that MyST generates are compatible with Sphinx but not with the normal Docutils pipeline.  This PR fixes one of the incompatibilities.  The [first example](https://myst-parser.readthedocs.io/en/latest/api/renderers.html#the-docutils-renderer) of the API docs is enough to demonstrate the issue:
````python
from myst_parser.main import to_docutils
document = to_docutils("""
Here's some *text*
1. a list
> a quote
{emphasis}`content`
```{sidebar} my sidebar
content
```
""")
from docutils.core import publish_from_doctree
print(publish_from_doctree(document, writer_name="latex").decode("utf-8"))
````
````
Traceback (most recent call last):
File "./minimal.py", line 19, in <module>
print(publish_from_doctree(document, writer_name="latex").decode("utf-8"))
File "…/docutils/core.py", …
```
> FIX: Add mandatory attributes on enumerated_list

- docs/index.md
Ref: https://twitter.com/juanluisback/status/1419626473787469824
Encouraged by @pradyunsg and @chrisjsewell 🚀
> 📚 DOCS: Add reference to MySTyc in landing page

- docs/api/parsers.md
- docs/api/reference.rst
- myst_parser/docutils_.py
- myst_parser/docutils_renderer.py
- myst_parser/sphinx_parser.py
- myst_parser/sphinx_renderer.py
- setup.cfg
- tests/test_commonmark/test_commonmark.py
- tests/test_renderers/fixtures/sphinx_roles.md
- tests/test_renderers/fixtures/syntax_elements.md
See https://github.com/executablebooks/markdown-it-py/releases/tag/v2.0.0,
and https://github.com/executablebooks/mdit-py-plugins/releases/tag/v0.3.0
closes #169
> ⬆️ UPGRADE: markdown-it-py v2, mdit-py-plugins v0.3

- docs/syntax/syntax.md
- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/tables.md
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx3.html
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx4.html
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx4.xml
- tox.ini
Change cell alignment classes to `text-left`, `text-center`, or `text-right`,
and allow tables with no body.
closes #412, closes #430
> 👌 IMPROVE: Table rendering

- myst_parser/mocking.py
> 🐛 FIX: Ensure parent files are re-built if include file changes

- myst_parser/parse_directives.py
- tests/test_renderers/fixtures/sphinx_directives.md
> 🐛 FIX: Convert empty directive option to `None`

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/syntax_elements.md
> 👌 IMPROVE: Add `\\` for hard-breaks in latex

- .pre-commit-config.yaml
- docs/conf.py
- docs/sphinx/reference.md
- docs/syntax/optional.md
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- myst_parser/mocking.py
- tests/test_sphinx/sourcedirs/fieldlist/conf.py
- tests/test_sphinx/sourcedirs/fieldlist/index.md
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_fieldlist_extension.sphinx3.html
- tests/test_sphinx/test_sphinx_builds/test_fieldlist_extension.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_fieldlist_extension.sphinx4.html
- tests/test_sphinx/test_sphinx_builds/test_fieldlist_extension.sphinx4.xml
Field lists are mappings from field names to field bodies,
based on the [reStructureText syntax](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#field-lists).
A prominent use case of field lists is for use in API docstrings, as used in [Sphinx's docstring renderers](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#the-python-domain).
This should hopefully pave the way for use with `sphinx.ext.autodoc`
> ✨ NEW: Add `fieldlist` extension

- docs/api/parsers.md
- docs/api/reference.rst
- docs/conf.py
- docs/docutils.md
- docs/index.md
- docs/sphinx/index.md
- docs/sphinx/use.md
- myst_parser/docutils_.py
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- myst_parser/sphinx_.py
- setup.cfg
- tests/test_docutils.py
- tests/test_sphinx/sourcedirs/include_from_rst/conf.py
- tests/test_sphinx/sourcedirs/include_from_rst/include.md
- tests/test_sphinx/sourcedirs/include_from_rst/index.rst
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_include_from_rst.xml
This is a follow-up to my previous PR (GH-418),  part of an effort (GH-420) to make myst_parser integrate better with Docutils.
This exposes (almost) all MyST configuration settings in docutils.conf, making it possible to configure myst_parser for use without Sphinx.
I've added a simple entry point to make it easier to experiment (the second commit on this branch).  Here's a quick demo:
```console
$ python3 -m myst_parser.docutils_ -h
...
Usage
=====
docutils_.py [options] [<source> [<destination>]]
Generates (X)HTML documents from standalone MyST sources.  Reads from <source>
(default is stdin) and writes to <destination> (default is stdout).  See
<http://docutils.sf.net/docs/user/config.html> for the full reference.
Options
=======
General Docutils Options
------------------------
... …
```
> ✨ NEW: Add Docutils MyST config and CLI

- .github/workflows/docutils_setup.py
- .github/workflows/tests.yml
- myst_parser/docutils_.py
This PR adds a workflow for releasing an additional package `myst-docutils`, which does not include install requirements on docutils or sphinx, to close #347 and allow docutils to utilise it in their package with no cyclic dependencies.
It does this by simply modifying the `setup.cfg` and `README.md` before the build.
The build is also tested against a range of docutils versions (e.g. to ensure it does not fail due to missing sphinx install)
> 🔧 MAINTAIN: Add publishing job for `myst-docutils`

- .github/workflows/docutils_setup.py
Seen at https://pypi.org/project/myst-docutils/
> 📚 DOCS: Fix myst-docutils README

- docs/sphinx/reference.md
- docs/syntax/optional.md
- myst_parser/main.py
If `False`, only links that contain a scheme (such as `http`) will be recognised as external links.
> ✨ NEW: Add `myst_linkify_fuzzy_links` option

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/amsmath.md
- tests/test_renderers/fixtures/sphinx_directives.md
- tests/test_renderers/fixtures/syntax_elements.md
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_footnotes.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.resolved.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.resolved.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.sphinx4.xml
This brings it inline with the AST produced by RST
> 👌 IMPROVE: Add `bullet` attribute to `bullet_list` node

- myst_parser/mocking.py
- tests/test_sphinx/sourcedirs/basic/content.md
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx3.html
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx4.html
- tests/test_sphinx/test_sphinx_builds/test_basic.sphinx4.xml
Previously `state.inline_text()` (used by some directives)
always parsed text with the `DocutilsRenderer`.
Now it will correctly use the `SphinxRenderer`,
when parsing with sphinx,
allowing for cross-document references to be handled.
> 👌 IMPROVE: Use correct renderer for `state.inline_text`

- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_renderers/test_error_reporting.py
Also runs transforms on the document.
> 🧪 TESTS: Use `publish_doctree` to test error reporting

- docs/api/parsers.md
- myst_parser/__init__.py
- myst_parser/cli.py
- myst_parser/directives.py
- myst_parser/docutils_.py
- myst_parser/main.py
- myst_parser/sphinx_parser.py
The `renderer` option has been removed from `MdParserConfig`,
since it is not a configuration for the parser.
Then the `default_parser` function has been replaced with `create_md_parser`,
which directly takes the renderer class as a 2nd argument.
> ♻️ REFACTOR: `default_parser` -> `create_md_parser`

- .github/workflows/tests.yml
- setup.cfg
- tox.ini
Python 3.6 end-of-life was 23 Dec 2021
> ⬆️ UPGRADE: Drop python 3.6, support 3.10

- myst_parser/docutils_.py
- setup.cfg
- tests/test_docutils.py
Move Myst config above RST.
Add logic for handling `line_length_limit` and `raw_enabled` settings,
in-line with `docutils/parsers/recommonmark_wrapper.py`
> 👌 IMPROVE: Docutils parser settings

- .github/workflows/tests.yml
- myst_parser/docutils_renderer.py
- tests/conftest.py
- tests/test_renderers/fixtures/syntax_elements.md
- tests/test_renderers/test_fixtures_docutils.py
- tests/test_renderers/test_fixtures_sphinx.py
For the docutils base HTML writer, it is expected that `field_body` contain block elements (e.g. `paragraph`) as children, rather than `Text`, meaning this file:
```markdown
---
a: 1
---
```
leads to:
```console
$ myst-docutils-html test.txt --traceback 
Traceback (most recent call last):
File "/path/bin/myst-docutils-html", line 33, in <module>
sys.exit(load_entry_point('myst-parser', 'console_scripts', 'myst-docutils-html')())
File "/path/lib/python3.7/site-packages/myst_parser/docutils_.py", line 248, in cli_html
_run_cli("html", "(X)HTML documents", argv)
File "/path/lib/python3.7/site-packages/myst_parser/docutils_.py", line 242, in _run_cli
argv=argv,
File "/path/lib/python3.7/site-packages/docutils/core.py", line 355, in publish_cmdline
config_section=config_section, …
```
> 🐛 FIX: front-matter rendering with docutils

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/docutil_syntax_elements.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
- tests/test_sphinx/sourcedirs/basic/content.md
- tests/test_sphinx/test_sphinx_builds.py
After PR #477, I noted that the `SmartQuote` transform was being applied to  the front-matter values,
before they were extracted to the document metadata (see also issue #479).
Therefore, we now add them as a `literal` to stop this happening.
> 🐛 FIX: Front matter -> sphinx metadata regression

- myst_parser/docutils_renderer.py
> 👌 IMPROVE: `note_refname` for docutils internal links

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/docutil_syntax_elements.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
- tests/test_sphinx/conftest.py
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.resolved.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.resolved.sphinx4.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.sphinx3.xml
- tests/test_sphinx/test_sphinx_builds/test_gettext_html.sphinx4.xml
Propagate the starting number of ordered lists to the docutils AST.
fixes #482
Equivalency with RST can now be seen with:
`test.txt`:
```
5. foo
6. bar
```
```console
$ rst2pseudoxml.py test.txt
<document source="test.txt">
<enumerated_list enumtype="arabic" prefix="" start="5" suffix=".">
<list_item>
<paragraph>
foo
<list_item>
<paragraph>
bar
$ myst-docutils-pseudoxml test.txt
<document source="test.txt">
<enumerated_list enumtype="arabic" prefix="" start="5" suffix=".">
<list_item>
<paragraph>
foo
<list_item>
<paragraph>
bar
```
> 🐛 FIX: Ordered list starting number

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/docutil_syntax_elements.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
i.e. "." for `1. a` and ")" for `1) a`
> 👌 IMPROVE: Propagate enumerated list suffix

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/docutil_syntax_elements.md
Minor improvement, to handle null lexer_name,
and allow for the use of an alternative node class.
> 👌 IMPROVE: `DocutilsRenderer.create_highlighted_code_block`

- myst_parser/docutils_renderer.py
- myst_parser/mocking.py
- myst_parser/parse_directives.py
- tests/test_renderers/fixtures/mock_include_errors.md
- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_renderers/test_parse_directives.py
- tests/test_renderers/test_parse_directives/test_parsing_Note___class__name_n_na_.yml
- tests/test_renderers/test_parse_directives/test_parsing_Note__a_.yml
- tests/test_renderers/test_parse_directives/test_parsing_Note_a__.yml
Previously, nested parsing of content within directives
would not correctly propagate the starting line number
of the content.
For example:
````markdown
Paragraph
```{note}
:class: abc
:name: xyz
{unknown}`a`
```
````
Would incorrectly report the error on line 1:
```
<string>:1: (ERROR/3) Unknown interpreted text role "unknown".
```
but now correctly reports on line 7:
```
<string>:7: (ERROR/3) Unknown interpreted text role "unknown".
```
> 🐛 FIX: Source line reporting for nested parsing

- .github/workflows/tests.yml
- setup.cfg
- tests/test_renderers/fixtures/docutil_directives.md
- tests/test_renderers/fixtures/docutil_roles.md
- tests/test_renderers/test_error_reporting.py
- tests/test_renderers/test_fixtures_docutils.py
- tests/test_renderers/test_fixtures_sphinx.py
- tests/test_renderers/test_include_directive.py
I created https://pypi.org/project/pytest_param_files/,
to simplify the fixture based testing 😄
> 🧪 TESTS: Use `pytest-param-files`

- myst_parser/docutils_renderer.py
- myst_parser/mocking.py
- myst_parser/sphinx_renderer.py
- tests/test_renderers/fixtures/reporter_warnings.md
Handle disallowed nested headings, by converting them to `rubric` nodes
closes #494
> 👌 IMPROVE: Convert nested headings to rubrics

- docs/sphinx/use.md
- myst_parser/directives.py
- myst_parser/docutils_renderer.py
- myst_parser/html_to_nodes.py
- myst_parser/main.py
- myst_parser/mocking.py
- myst_parser/sphinx_renderer.py
- tests/test_html/test_html_to_nodes.py
- tests/test_html/test_parse_html.py
- tests/test_renderers/fixtures/reporter_warnings.md
Internal improvements, that should mainly not be noticed by users
> 🔀 MERGE: Internal improvements to the code base

- docs/sphinx/reference.md
- docs/syntax/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_renderers/test_error_reporting.py
- tests/test_renderers/test_myst_config.py
This is the "simplest" implementation (3 extra lines!).
Basically, it treats this:
```markdown
---
title: "A **title**"
---
```
like this (including parsing nested syntax)
```markdown
```
I'm not sure if this would be the correct/expected implementation though
for example, currently
```markdown
---
title: "A **title**"
---
```
would be treated as
```markdown
```
but should it instead be treated as
```markdown
```
(also, on a technical note, the parsing should be a bit smarter, in only allowing inline syntax,
there should probably also be a config to turn it off/on)
> ✨ NEW: Add `myst_title_to_header` configuration

- myst_parser/docutils_renderer.py
- tests/test_renderers/fixtures/myst-config.txt
Linkify links should always be treated as external links,
and the child text should be rendered (rather than using the href)
> 🐛 FIX: linkify link rendering

- docs/conf.py
- docs/docutils.md
- docs/syntax/optional.md
- docs/syntax/syntax.md
- myst_parser/docutils_renderer.py
- myst_parser/main.py
- tests/test_renderers/fixtures/myst-config.txt
The `strikethrough` extension allows text within `~~` delimiters to have a strikethrough (horizontal line) placed over it.
For example, `~~strikethrough with *emphasis*~~`.
Note, this extension is currently only supported for HTML output,
and will generate a `myst.strikethrough` warning
(since docutils does not have a native strikethrough node).
> ✨ NEW: Add `strikethrough` extension

- CHANGELOG.md
- docs/syntax/optional.md
- myst_parser/__init__.py
I think this is just about good to go!
I have essentially been running a "feedback loop" with https://github.com/executablebooks/MyST-NB/pull/380, to ensure everything will be fine running these changes up to myst-nb and jupyter-book (see https://github.com/executablebooks/jupyter-book/issues/1608)
My only slight "concerns" are:
1. With #467, a few people might complain about some subtle changes to link identification (e.g. that links with `#` are no longer "automatically" treated as external), although it should be very rare
2. With #505, again people might not notice, and then complain it is not working
I think both these changes are good/necessary, it is just the backward dependency consideration (although I would hope people have suitably pinned to `~=0.16.0`)
---
**Dollarmath is now …
> 🚀 RELEASE: 0.17.0

- CHANGELOG.md
- docs/syntax/optional.md
This updates our auto-generated header anchor documentation to have a bit more structure to it so that it's a bit easier to follow. It also adds a few warnings to our CHANGELOG so that we boost visibility of a recent breaking change.
> 📚 DOC: Update auto-generated header anchors section

- myst_parser/myst_refs.py
- myst_parser/sphinx_renderer.py
For sphinx parallel builds, `env.myst_anchors` will be discarded when merging environments from the parallel jobs.
So we no longer use this to check whether to look for heading anchors
closes #411
> 🐛 FIX: Heading anchor resolution for parallel builds

- .pre-commit-config.yaml
See https://github.blog/2021-09-01-improving-git-protocol-security-github/
> 🔧 MAINTAIN: Change git to https in pre-commit-hooks

- tests/test_renderers/fixtures/sphinx_roles.md
- tests/test_renderers/test_fixtures_sphinx.py
> 🧪 TESTS: Fix test failure with Sphinx 4.5

- CHANGELOG.md
2022 is the new 2021 (date typo in CHANGELOG)
> 📚 DOCS: Fix date of  0.17.0 release

- docs/sphinx/index.md
The phrase "allows you to use write Sphinx documentation" includes an extra word because of an editing oversight. I think the writer means "allows you to write Sphinx documentation" etc. My guess is that in a previous draft, the writer had "allows you to use MyST to write Sphinx documentation," and didn't fully complete the revision.
> 📚 DOCS: Fix typo - "to use write Sphinx"

- tests/test_renderers/test_fixtures_sphinx.py
Fixes `test_sphinx_directives[35-highlight (sphinx.directives.code.Highlight):]` which was failing on 32-bit platforms due to `linenothreshold` defaulting to `sys.maxsize`.
Fixes: #522
> 🧪 TESTS: Fix regression output on 32-bit systems to match 64-bit systems

- pyproject.toml
This dependency has been removed from markdown-it-py,
so needs to be directly declared here
(https://github.com/executablebooks/markdown-it-py/pull/212)
> 🔧 MAINTAIN: Directly specify attrs dependency

- docs/conf.py
- myst_parser/dc_validators.py
- myst_parser/docutils_.py
- myst_parser/main.py
- pyproject.toml
- tests/test_docutils.py
> ♻️ REFACTOR: Replace attrs by dataclasses

- myst_parser/__init__.py
This is already validated by myst-parser
closes #558
> 👌 IMPROVE: Do not let sphinx check the config type

- myst_parser/config/dc_validators.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/sphinx_ext/myst_refs.py
Improve integration with myst-nb
> 🔧 MAINTAIN: Minor fixes

- myst_parser/cli.py
Ideally it would read from sphinx `source_encoding`,
but this should fix most use cases, with the default encoding.
closes #609
> 🐛 FIX: set myst-anchor read/write encoding as `utf8`

- .github/workflows/tests.yml
- myst_parser/mdit_to_docutils/base.py
- pyproject.toml
- tests/test_renderers/fixtures/docutil_roles.md
- tests/test_renderers/test_fixtures_docutils.py
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_footnotes.sphinx5.html
This PR allows docutils 0.19 to be used with myst-parser.
See: https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-19-2022-07-05.
Note though, it does not fix a number of `DeprecationWarning` that arise from using docutils 0.19, which will be addressed at a later date.
closes #591
> ⬆️ UPGRADE: docutils 0.19 support

- .pre-commit-config.yaml
- docs/conf.py
- docs/syntax/optional.md
- myst_parser/config/main.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/parsers/mdit.py
- pyproject.toml
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_renderers/test_myst_config.py
Use inline attributes to configure MD images:
`![alt](img/fun-fish.png){#id .class width="100px" align=center}`
> ✨ NEW: Add `attrs_image` (experimental) extension

- docs/syntax/optional.md
- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/docutil_syntax_elements.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
- tests/test_sphinx/test_sphinx_builds/test_basic.html
- tests/test_sphinx/test_sphinx_builds/test_basic.resolved.xml
- tests/test_sphinx/test_sphinx_builds/test_basic.xml
Sphinx will output reftitle as the HTML title attr.
See: https://github.com/sphinx-doc/sphinx/blob/6e6b9ad45194177811551c77f5f4040213d1c661/sphinx/writers/html5.py#L227
> 👌 Reference attributes title -> reftitle

- .github/dependabot.yml
- .github/workflows/test-formats.yml
- .github/workflows/tests.yml
Provides dependabot configuration to check weekly if there is a new version available. It creates or replace a pr per dependency. I defined a prefix as I saw that you are using the up arrow for dependency upgrades.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> ci(deps): setup dependabot 

- docs/live_preview.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/warnings_.py
- tests/test_renderers/fixtures/directive_options.md
- tests/test_renderers/fixtures/mock_include_errors.md
- tests/test_renderers/fixtures/reporter_warnings.md
If an unknown directive/role name is encountered,
then a warning is emitted with the `myst.directive_unknown` or `myst.role_unknown` type,
which can be suppressed.
> 👌 Change missing directive/role errors to warnings

- docs/syntax/optional.md
- myst_parser/config/main.py
- myst_parser/parsers/docutils_.py
- tests/test_renderers/fixtures/myst-config.txt
`myst_heading_slug_func` can now also be set to a string,
which will be interpreted as an import path to a function,
e.g. `myst_heading_slug_func = "mypackage.mymodule.slugify"`.
> 👌 IMPROVE: Allow heading_slug_func to be a string 

- .pre-commit-config.yaml
- docs/conf.py
- docs/syntax/optional.md
- docs/syntax/syntax.md
- myst_parser/config/main.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/parsers/mdit.py
- pyproject.toml
- tests/test_renderers/fixtures/attributes.md
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_renderers/test_fixtures_docutils.py
- tests/test_renderers/test_fixtures_sphinx.py
- tests/test_sphinx/test_sphinx_builds/test_fieldlist_extension.xml
- tox.ini
By adding `"attrs_block"` to `myst_enable_extensions` (in the sphinx `conf.py`), you can enable parsing of inline attributes after certain inline syntaxes. This is adapted from [djot block attributes](https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#block-attributes)
> ✨ NEW: Add `attrs_block` extension

- myst_parser/cli.py
- myst_parser/config/main.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/parsers/mdit.py
- myst_parser/warnings_.py
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_renderers/test_myst_config.py
For use with the `attrs_block` extension.
This just moves around the logic for implicit heading anchors a bit (without changing anything user facing), to allow distinguishing between explicit and implicit heading ids.
> 👌 IMPROVE: Allow setting {#id} on headings

- docs/_static/local.css
Minor fix to stop the hover tips getting heading numbers
> 📚 DOCS: fix tip CSS

- codecov.yml
- myst_parser/mdit_to_docutils/base.py
- myst_parser/mdit_to_docutils/sphinx_.py
- myst_parser/mdit_to_docutils/transforms.py
- myst_parser/parsers/docutils_.py
- myst_parser/parsers/sphinx_.py
- myst_parser/sphinx_ext/myst_refs.py
- tests/test_renderers/fixtures/docutil_link_resolution.md
- tests/test_renderers/fixtures/docutil_syntax_elements.md
- tests/test_renderers/fixtures/sphinx_link_resolution.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
- tests/test_renderers/test_fixtures_docutils.py
- tests/test_renderers/test_fixtures_sphinx.py
- tests/test_renderers/test_myst_refs.py
- tests/test_renderers/test_myst_refs/duplicate.xml
- tests/test_renderers/test_myst_refs/missing.xml
This PR moves myst-parser in the direction of https://github.com/executablebooks/myst-enhancement-proposals/pull/10, in a relatively back compatible manner, and in a way that supports both docutils and sphinx.
It expands the capability of `[](#id)` to more than just linking to heading slugs, with the order of specificity being:
1. If it matches a local (to that document) "explicit" `std:ref` target, then link to that and stop
- Note, currently only `std:ref` domain/type are supported, e.g. not `math` etc. That's more difficult and can come later
2. If it matches a local (to that document) "implicit" heading slug, then link to that and stop
3. If using docutils (i.e. single-page) build, then stop here and emit a `myst.xref_missing` warning
4. If using sphinx then create a `pending_xref` …
> 👌 Enhance `[](#id)` references

- docs/syntax/optional.md
- myst_parser/mdit_to_docutils/base.py
- myst_parser/parsers/docutils_.py
- myst_parser/sphinx_ext/main.py
- tests/test_renderers/fixtures/containers.md
- tests/test_sphinx/sourcedirs/extended_syntaxes/index.md
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.html
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.xml
At present, colon fences without a directive specified (e.g. `:::{note}`) are treated as code bocks 
```
:::name
Some text
:::
```
```xml
<code language=name>
Some text
```
In keeping with the purpose of these block, as containers for nested MyST content, they are now converted to:
```xml
<div class=name>
<paragraph>
Some text
```
This is also in keeping with the original pandoc/djot inspiration <https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#div>
> 👌 Improve: Non-directive colon-fences

- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/containers.md
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.html
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.xml
Minor fix to the last commit :sweat_smile:
> 🐛 FIX: colon_fence wrapping

- myst_parser/mdit_to_docutils/base.py
- myst_parser/mdit_to_docutils/transforms.py
- tests/test_renderers/fixtures/docutil_link_resolution.md
- tests/test_renderers/fixtures/sphinx_link_resolution.md
For example `<#name with spaces>` will be encoded as `#name%20with%20spaces`, so we need to decode before resolving the reference.
> 🐛 FIX encoded URL ID references

- myst_parser/mdit_to_docutils/base.py
- myst_parser/mdit_to_docutils/sphinx_.py
- myst_parser/mdit_to_docutils/transforms.py
- myst_parser/sphinx_ext/myst_refs.py
- tests/test_renderers/fixtures/sphinx_link_resolution.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
- tests/test_sphinx/sourcedirs/references/conf.py
- tests/test_sphinx/sourcedirs/references/index.md
- tests/test_sphinx/sourcedirs/references/objects.inv
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_basic.xml
- tests/test_sphinx/test_sphinx_builds/test_references.html
- tests/test_sphinx/test_sphinx_builds/test_references.resolved.xml
- tests/test_sphinx/test_sphinx_builds/test_references.xml
Previously, if `[](#target)` matched nothing locally, but multiple items in intersphinx inventories, then no warning would be logged, and the first match silently used.
Resolution of intersphinx now proceeds (if no local matches found) the same as for `[](inv:#target)`, such that a `myst.iref_ambiguous` warning is emitted in this case (the first match is then still used).
Warnings coming from resolution of `[](#target)` can also now be "individually" turned off using https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpick_ignore, e.g. `nitpick_ignore = [("myst", "target")]`
> 👌 Improve `[](#target)` resolution warnings

- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/docutil_syntax_elements.md
- tests/test_renderers/fixtures/sphinx_syntax_elements.md
This commit builds on ac111ea6f58508b0987091595edfb33db1ee033f,
to allow for implicit heading slugs to be applied also to nested headings,
i.e. so they can be referenced in Markdown links
> 👌 Improve: Apply implicit targets to nested headings

- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_sphinx/sourcedirs/extended_syntaxes/conf.py
- tests/test_sphinx/sourcedirs/extended_syntaxes/index.md
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.html
- tests/test_sphinx/test_sphinx_builds/test_extended_syntaxes.xml
MyST follows http://johnmacfarlane.net/pandoc/README.html#definition-lists, to denote lists of term -> definition.
```markdown
Term 1
: Definition
Term 2
: Definition
```
It should be easy for users to turn one of these lists into a glossary,
where each term is uniquely referenceable across the entire project.
(note I don't think this should be "on by default", because there are many use cases where this is not desirable and would lead to many reference clashes, plus that would be breaking in myst-parser and so not really viable)
Sphinx has a [glossary directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-glossary), however, this hard-codes in the parsing of their definition lists to have a subtly different syntax to that above, with no `:`
(see …
> ✨ New: add .glossary for attrs_block

- docs/conf.py
The announcement text at the top was having a base pydata theme color applied to it because it was wrapped in `<p>`, the simplest fix is just to un-wrap it for now, though this should probably be made more robust in the pydata theme as well.
> 📚 DOCS: Un-wrap announcement in <p>

- docs/intro.md
Under the `## Extending Sphinx` heading, the text of the example discusses `sphinx-design`, but the pip install command was installing `sphinxcontrib.mermaid`. I see there is a commented-out example, below, which is related to mermaid, so perhaps this was missed in a copy/paste.
> 📚 Fix the sphinx-design example

- myst_parser/config/main.py
- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/myst-config.txt
closes #366
Setting the following config, for example:
```python
extensions = ["myst_parser", "sphinxcontrib.mermaid"]
myst_fence_as_directive = ["mermaid"]
myst_enable_extensions = ["attrs_block"]
```
allows for one to write
````markdown
{caption="My caption"}
{alt="HTML alt" align=center}
```mermaid
graph LR
a --> b
```
````
and have interoperable rendering with places like GitHub:
{caption="My caption"}
{alt="HTML alt" align=center}
```mermaid
graph LR
a --> b
```
> ✨ NEW: Add `myst_fence_as_directive` config

- .pre-commit-config.yaml
- docs/conf.py
- myst_parser/_compat.py
- myst_parser/_docs.py
- myst_parser/config/dc_validators.py
- myst_parser/config/main.py
- myst_parser/inventory.py
- myst_parser/parsers/docutils_.py
- pyproject.toml
- tests/test_docutils.py
> ⬆️ UPGRADE: Drop Python 3.7

- .pre-commit-config.yaml
- pyproject.toml
- tests/test_renderers/fixtures/docutil_syntax_extensions.txt
See https://github.com/executablebooks/markdown-it-py/releases/tag/v3.0.0 and https://github.com/executablebooks/mdit-py-plugins/releases/tag/v0.4.0
> ⬆️ UPGRADE: markdown-it-py v3

- .github/workflows/tests.yml
This adds a GHA job that reliably determines if all the required dependencies have succeeded or not.
It also allows to reduce the list of required branch protection CI statuses to just one — `check`. This reduces the maintenance burden by a lot and have been battle-tested across a small bunch of projects in its action form and in-house implementations of other people.
This action is now in use in aiohttp (and other aio-libs projects), CherryPy, conda, coveragepy, Open edX, Towncrier some of the Ansible repositories, pip-tools, all of the jaraco's projects (like `setuptools`, `importlib_metadata`), some of hynek's projects (like `attrs`, `structlog`), some PyCQA, PyCA, PyPA and pytest projects, a few AWS Labs projects. Admittedly, I maintain a few of these but it seems to address some of …
> 🧪 Introduce a gate/check GHA job

- myst_parser/config/dc_validators.py
- myst_parser/config/main.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/warnings_.py
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_sphinx/sourcedirs/substitutions/index.md
- tests/test_sphinx/test_sphinx_builds/test_substitutions.html
- tests/test_sphinx/test_sphinx_builds/test_substitutions.xml
Allow any value type (including dict, list, datetime) and emit a `myst.substitution` warning for errors in resolving the substitution.
> 👌 IMPROVE: Substitution extension

- myst_parser/mdit_to_docutils/base.py
- tests/test_sphinx/sourcedirs/references/index.md
- tests/test_sphinx/test_sphinx_builds/test_references.html
- tests/test_sphinx/test_sphinx_builds/test_references.resolved.xml
- tests/test_sphinx/test_sphinx_builds/test_references.xml
This can be easily tested by visiting the source markdown page on github:
https://github.com/Cimbali/MyST-Parser/blob/master/tests/test_sphinx/sourcedirs/references/index.md#image-in-title-
Fixes #752.
----
Note that for the `nested $a=1$` case I’ve updated the test to match the new behaviour, to allow improving matching github behaviour bit by bit.
Neither the old or new test match Github behaviour:
https://github.com/executablebooks/MyST-Parser/blob/master/tests/test_sphinx/sourcedirs/references/index.md#title-with-nested-a1
The issue seems to be math-to-text conversion (so the trailing `-` added by this PR is “more correct” even though not 100% there).
> 👌 Improve default slug generation for heading anchors

- docs/develop/contributing.md
Fix executablebooks/MyST-Parser#791
> 📚 Add linkify dependency to contributing docs.

- docs/syntax/math.md
- The double `used` seems a typo?
https://github.com/executablebooks/MyST-Parser/blob/350c6331da4738057556d966b0bfd9d98d570352/docs/syntax/math.md?plain=1#L9
- `docs/syntax/math.md`
- Remove the redundant `used`.
> 📚 Fix the double `used` in docs/syntax/math.md

- docs/.gitignore
- docs/syntax/optional.md
- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/attributes.md
This is in keeping with the restructured text implementation, e.g.
```restructuredtext
Hallo
-- Chris Sewell `link <https://source.com>`__
```
tokenizes to:
```xml
<document source="test.rst">
<block_quote>
<paragraph>
Hallo
<attribution>
Chris Sewell 
<reference name="link" refuri="https://source.com">
link
```
> 👌 Nested parse attribution in `attr_block`

- myst_parser/_docs.py
- myst_parser/mdit_to_docutils/base.py
- pyproject.toml
- tests/test_docutils.py
- tests/test_renderers/test_fixtures_docutils.py
- tests/test_renderers/test_myst_config.py
This PR fixes the deprecation warnings raised by docutils' deprecation of `OptionParser`.
The help handling is a little ugly - we could introduce a switch on the docutils version like we do for the default settings. However, I *think* this approach will be less likely to break once the breaking change is introduced.
> 🔧 Fix docutils deprecation in option parsing

- myst_parser/mdit_to_docutils/base.py
- myst_parser/mocking.py
- myst_parser/parsers/directives.py
- myst_parser/warnings_.py
- tests/test_renderers/fixtures/directive_options.md
- tests/test_renderers/fixtures/directive_parsing.txt
- tests/test_renderers/fixtures/myst-config.txt
- tests/test_renderers/fixtures/reporter_warnings.md
- tests/test_renderers/test_parse_directives.py
Minor improvement to the specificity of warnings regarding problems encountered when parsing directives
> 👌 Improve directive parsing warnings

- pyproject.toml
`no_implicit_optional` is the default value in mypy these days, so this config is redundant
> 🔧 remove redundant mypy config

- myst_parser/inventory.py
- myst_parser/mdit_to_docutils/base.py
- myst_parser/mocking.py
- myst_parser/parsers/docutils_.py
- pyproject.toml
- make mypy config stricter by disallowing 'any' generics
- fix some errors by adding generics
- 'whitelist' the modules with excessive errors
- includes some changes due to autoformatting `pyproject.toml`
this whitelist should be shrunk and eventually removed over time. It should never get larger.
> 🔧 mypy- disallow 'any generics'

- myst_parser/config/main.py
- myst_parser/mdit_to_docutils/base.py
- tests/test_renderers/fixtures/myst-config.txt
Add support to enable external links to open in a new tab. Expose the configuration option myst_links_external_new_tab, which if set will set all URL links to open in a new tab on the browser.
Besides that, we allow the user to set the target and rel attributes when using the extension inline_attrs (#820).
Closes #820
Closes #856
> 👌 IMPROVE: Allow for opening external links in new tabs (#856)

- myst_parser/mocking.py
- tests/test_sphinx/sourcedirs/includes/index.md
- tests/test_sphinx/test_sphinx_builds.py
- tests/test_sphinx/test_sphinx_builds/test_includes.html
- tests/test_sphinx/test_sphinx_builds/test_includes.xml
Adds emission of Sphinx `include-read` events while processing include directives, closes #881.
[include-read](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-include-read)
If there is a better way to restrict the test to Sphinx>=7.5.2, please let me know.
> :sparkles: NEW: Emits sphinx include-read event

- docs/syntax/typography.md
- myst_parser/mocking.py
- tests/test_renderers/fixtures/docutil_directives.md
The `line-block` directive constructs a block where all line breaks (and also initial indentations) are respected.
This was not previously supported, due to a missing State method
> ✨ Allow for use of the `line-block` directive

- docs/syntax/admonitions.md
Correct admonition example to match class option definition which is a space-separated list.
Add a link to the class option definition for identifier normalization rules.
https://docutils.sourceforge.io/docs/ref/rst/directives.html#identifier-normalization
> 📚 DOCS: Fix admonition example

- docs/syntax/optional.md
Just a minor typo I saw while reading MathJax docs. Changed "ensurea" to "ensures".
> 📚 Fix typo

- docs/develop/architecture.md
Complete sentence referring to Markdown-It-Py project.
> 📚 Fix architecture typo (#855)

- myst_parser/parsers/directives.py
- myst_parser/parsers/options.py
- tests/test_renderers/fixtures/directive_parsing.txt
- tests/test_renderers/fixtures/option_parsing.yaml
- tests/test_renderers/test_parse_directives.py
> 🐛 FIX empty value for final directive option

- myst_parser/parsers/directives.py
- tests/test_renderers/fixtures/directive_parsing.txt
> 🐛 FIX: allow indented option block

- .github/workflows/tests.yml
- pyproject.toml
- tox.ini
The Python 3.13 release candidate is out now! :rocket:
The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0-release-candidate-1-released/59703?u=hugovk]):
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc1 **will work** with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).
> 🧪 Add CI testing support for Python 3.13

- CHANGELOG.md
- docs/develop/background.md
- docs/syntax/cross-referencing.md
- docs/syntax/math.md
- docs/syntax/optional.md
- myst_parser/mdit_to_docutils/sphinx_.py
- myst_parser/parsers/directives.py
- myst_parser/warnings_.py
https://pypi.org/project/codespell
% `codespell --ignore-words-list=nd,rsource --quiet-level=3`
```
./CHANGELOG.md:171: suppressable ==> suppressible
./CHANGELOG.md:172: suppressable ==> suppressible
./docs/develop/background.md:25: converstaion ==> conversation
./docs/syntax/cross-referencing.md:17: bloc ==> block
./docs/syntax/math.md:74: multline ==> multiline
./docs/syntax/optional.md:221: multline ==> multiline
./myst_parser/warnings_.py:58: occured ==> occurred
./myst_parser/parsers/directives.py:272: convertor ==> converter
./myst_parser/parsers/directives.py:279: convertor ==> converter
./myst_parser/parsers/directives.py:284: convertor ==> converter
./myst_parser/mdit_to_docutils/sphinx_.py:185: referencable ==> referenceable
```
% `codespell --ignore-words-list=nd,rsource …
> 📚 Fix typos discovered by codespell

- myst_parser/mocking.py
> 🔧 Fix type of MockIncludeDirective’s `klass` parameter

- docs/syntax/roles-and-directives.md
I think this paragraph is redundant here.
> 📚 remove redundant paragraph
