executablebooks/MyST-Parser

myst_parser/docutils_renderer.py
myst_parser/span_tokens.py
tests/sphinx/sourcedirs/basic/content.md
tests/sphinx/test_sphinx_builds/test_basic.html
tests/test_docutils_renderer.py

You can now do e.g.
```
(header_target)= 
{ref}`header_target`
```

Add Target span token

---

docs/syntax.md

This adds a few tables in the syntax page to compare one vs the other...what do folks think? Good way to compare?

adding rst tables comparison

---

myst_parser/block_tokens.py
myst_parser/docutils_renderer.py
tests/sphinx/sourcedirs/basic/content.md
tests/sphinx/test_sphinx_builds/test_basic.html

Add default language retrieval for code fences

---

.circleci/config.yml
.readthedocs.yml
docs/index.md
setup.py

Since these are not core requirements of the Sphinx parser

Split requirements for RTD documentation build into separate extra

---

docs/develop/architecture.md
docs/develop/index.md
docs/examples/wealth_dynamics_md.md
docs/examples/wealth_dynamics_rst.rst
docs/index.md
docs/using/index.md
docs/using/install.md

This adds a few more pieces of documentation and refactors some pieces of the docs. It also adds links to source files for the examples

adding documentation

---

myst_parser/docutils_renderer.py

This wraps a bit of the FrontMatter renderer into a hidden function that could be reused to copy the same logic. I imagine that over time, this could also be where serialization happens etc...it'd be good if, whenever that happens, we can easily pull the same behavior into sphinx-notebook so I think this is an easy way to do so.
Doesn't change any behavior, only cosmetics

tiny convenience func to encode a dict as a docinfo node

---

docs/using/index.md
docs/using/install.md
docs/using/sphinx.md
docs/using/use_api.md
myst_parser/__init__.py
myst_parser/block_tokens.py
myst_parser/docutils_renderer.py
myst_parser/html_renderer.py
tests/test_renderers/conftest.py
tests/test_renderers/test_docutils.py
tests/test_renderers/test_html.py
tests/test_renderers/test_roles_directives.py
tests/test_syntax/test_ast.py

Add API documentation and supporting code (particularly improving the sphinx mock environment).
See https://161-240151150-gh.circle-artifacts.com/0/html/using/use_api.html
closes #70

Add API documentation and supporting code

---

docs/using/benchmark.md

Part of the benchmark, but then shows up in the document sidebar

remove unintended H1 header

---

docs/develop/test_infrastructure.md

Add documentation on `pytest-regressions`

---

docs/using/use_api.md
myst_parser/block_tokens.py
myst_parser/html_renderer.py
tests/test_commonmark/test_commonmark.py
tests/test_renderers/test_html.py
tests/test_renderers/test_html/test_minimal_html_page.html

Implement basic render methods for all MyST syntax

Implement HTMLRenderer methods

---

.circleci/config.yml
.readthedocs.yml
.travis.yml
README.md
docs/requirements.txt
docs/using/install.md
myst_parser/__init__.py
setup.py

Move to `mistletoe-ebp` dependency

---

docs/index.md

@jstac liked this one so I put it in the docs :-)

one liner in docs

---

docs/index.md

Update sphinx documentation link

---

.github/workflows/tests.yml

Testing out building docs with GHA
closes #177

docs in gha

---

myst_parser/myst_refs.py
myst_parser/sphinx_renderer.py
tests/test_renderers/test_myst_refs.py
tests/test_renderers/test_myst_refs/doc.xml
tests/test_renderers/test_myst_refs/doc.yml
tests/test_renderers/test_myst_refs/doc_nested.xml
tests/test_renderers/test_myst_refs/doc_nested.yml
tests/test_renderers/test_myst_refs/doc_with_extension.xml
tests/test_renderers/test_myst_refs/doc_with_extension.yml
tests/test_renderers/test_myst_refs/duplicate.xml
tests/test_renderers/test_myst_refs/duplicate.yml
tests/test_renderers/test_myst_refs/missing.xml
tests/test_renderers/test_myst_refs/missing.yml
tests/test_renderers/test_myst_refs/null.xml
tests/test_renderers/test_myst_refs/null.yml
tests/test_renderers/test_myst_refs/ref.xml
tests/test_renderers/test_myst_refs/ref.yml
tests/test_renderers/test_myst_refs/ref_nested.xml
tests/test_renderers/test_myst_refs/ref_nested.yml

this is result of discussion in https://github.com/sphinx-doc/sphinx/pull/8060

🧪 TEST: refactor test for sphinx warning

---

docs/using/intro.md
myst_parser/__init__.py
myst_parser/docutils_renderer.py
myst_parser/myst_refs.py
myst_parser/sphinx_parser.py
tests/test_renderers/test_myst_refs/missing.xml

Will now work with intersphinx, recognised URI schemas can be configured, and warning messages are better formatted

👌IMPROVE: myst refs

---

docs/using/howto.md
myst_parser/docutils_renderer.py
myst_parser/mocking.py
myst_parser/utils.py
tests/test_sphinx/conftest.py
tests/test_sphinx/sourcedirs/includes/include1.inc.md
tests/test_sphinx/sourcedirs/includes/subfolder/include2.inc.md
tests/test_sphinx/test_sphinx_builds.py
tests/test_sphinx/test_sphinx_builds/test_includes.html
tests/test_sphinx/test_sphinx_builds/test_includes.xml

This allows for local image references to be located correctly, when including from a file in a sub/super folder.
This commit also consolidates some code into `is_external_url`

✨ NEW: Add`relative-images` option to includes

---

docs/using/syntax.md

add a clarification about shorthand frontmatter

---

.pre-commit-config.yaml
docs/api/renderers.rst
docs/conf.py
docs/using/syntax.md
myst_parser/__init__.py
myst_parser/docutils_renderer.py
myst_parser/html_to_nodes.py
myst_parser/main.py
myst_parser/mathjax.py
myst_parser/mocking.py
myst_parser/myst_refs.py
myst_parser/parse_directives.py
myst_parser/parse_html.py
myst_parser/py.typed
myst_parser/sphinx_parser.py
myst_parser/sphinx_renderer.py
myst_parser/utils.py
tests/test_html/test_html_to_nodes.py
tests/test_html/test_parse_html.py
tests/test_renderers/test_error_reporting.py
tests/test_renderers/test_fixtures.py
tests/test_renderers/test_include_directive.py
tests/test_renderers/test_myst_refs.py
tests/test_renderers/test_parse_directives.py
tests/test_sphinx/conftest.py
tests/test_sphinx/test_sphinx_builds.py
tox.ini

👌 IMPROVE: Add isort and mypy type checking

---

docs/conf.py
docs/using/intro.md
docs/using/syntax.md
myst_parser/docutils_renderer.py
myst_parser/main.py

✨ NEW: Add `myst_footnote_transition` configuration

---

.pre-commit-config.yaml
myst_parser/__init__.py
myst_parser/docutils_renderer.py
myst_parser/main.py
myst_parser/mathjax.py
myst_parser/mocking.py
myst_parser/myst_refs.py
myst_parser/sphinx_parser.py
myst_parser/sphinx_renderer.py
setup.cfg
tests/test_renderers/fixtures/containers.md
tests/test_sphinx/sourcedirs/extended_syntaxes/index.md
tests/test_sphinx/test_sphinx_builds.py

- Configuration variables: `myst_admonition_enable`, `myst_figure_enable`, `myst_dmath_enable`, `myst_amsmath_enable`, `myst_deflist_enable`, `myst_html_img_enable`
- `:::{admonition,class}` -> `:::{admonition}\n:class: class`
- `:::{figure}` -> `:::{figure-md}`

⬆️ UPGRADE: markdown-it-py v1 

---

myst_parser/docutils_renderer.py
tests/test_sphinx/sourcedirs/footnotes/footnote_md.md
tests/test_sphinx/test_sphinx_builds/test_footnotes.html
tests/test_sphinx/test_sphinx_builds/test_footnotes.xml

🐛 FIX: Extract nested footnotes

---

docs/conf.py
setup.cfg

Adds the opengraph extension so that we get social previews for links

📚 DOCS: Add opengraph extension

---

setup.cfg

closes https://github.com/executablebooks/MyST-Parser/issues/398

🔧 MAINTAIN: Pin Sphinx minimum version to 3.1

---

docs/index.md

📚 DOCS: Fix gallery link

---

.readthedocs.yml
docs/_static/local.css
docs/conf.py
docs/syntax/optional.md
pyproject.toml

Inspired by @rowanc1, I created https://sphinx-tippy.readthedocs.io 😄

📚 DOCS: Add the sphinx-tippy extension

---

docs/conf.py
myst_parser/config/main.py
myst_parser/parsers/mdit.py
tests/test_renderers/fixtures/myst-config.txt

@asmeurer is this what you are after?

👌 Add `myst_enable_checkboxes` config

---

CHANGELOG.md
docs/live-preview.md
myst_parser/__init__.py

🎉 **MyST-Parser 1.0.0** 🎉
This changes absolutely nothing in the code, or about the maintenance/release policy of this project.
But it does feel about time 😄

🚀 RELEASE: v1.0.0

---

.github/workflows/tests.yml
pyproject.toml

See https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-20-2023-05-04

⬆️ UPGRADE: allow docutils v0.20.x

---

.github/workflows/tests.yml
pyproject.toml
tests/test_docutils.py
tests/test_sphinx/test_sphinx_builds.py
tests/test_sphinx/test_sphinx_builds/test_footnotes.html
tox.ini

See https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/CHANGES#LL58C1-L58C1

⬆️ UPGRADE: sphinx 7, drop sphinx 5

---

tests/test_renderers/fixtures/mock_include.md
tests/test_renderers/fixtures/sphinx_directives.md
tests/test_renderers/test_fixtures_sphinx.py
tests/test_renderers/test_include_directive.py
tests/test_renderers/test_myst_refs.py
tests/test_sphinx/conftest.py
tests/test_sphinx/test_sphinx_builds.py
tests/test_sphinx/test_sphinx_builds/test_fieldlist_extension.xml
tests/test_sphinx/test_sphinx_builds/test_includes.html
tests/test_sphinx/test_sphinx_builds/test_includes.xml

Fix tests broken by recent sphinx releases, up to sphinx v7.2.6
Note this also identified a regression by Sphinx: https://github.com/sphinx-doc/sphinx/issues/11689

🧪 Fix Sphinx 7.2 tests

---

README.md

See <https://github.com/executablebooks/MyST-Parser/pull/792>

📚 Also add linkify to pip install command in README

---

.github/workflows/test-formats.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
.readthedocs.yml
CHANGELOG.md
docs/conf.py
docs/index.md
myst_parser/_compat.py
myst_parser/_docs.py
myst_parser/config/dc_validators.py
myst_parser/config/main.py
myst_parser/inventory.py
myst_parser/mdit_to_docutils/base.py
myst_parser/mdit_to_docutils/transforms.py
myst_parser/parsers/directives.py
myst_parser/parsers/docutils_.py
myst_parser/parsers/mdit.py
myst_parser/parsers/options.py
myst_parser/parsers/parse_html.py
myst_parser/sphinx_ext/main.py
myst_parser/sphinx_ext/myst_refs.py
myst_parser/warnings_.py
pyproject.toml
tests/test_renderers/test_fixtures_docutils.py
tests/test_renderers/test_fixtures_sphinx.py
tests/test_renderers/test_myst_config.py
tests/test_renderers/test_myst_refs.py
tests/test_sphinx/sourcedirs/mathjax/conf.py
tests/test_sphinx/test_sphinx_builds.py
tox.ini

dropping support for lower versions

⬆️ Support python>=3.10, sphinx >=7,<9, docutils>=0.19,<0.22
